import type { Deal } from './types';

export const deals: Deal[] = [
  {
    id: "1",
    title: "Ração Hill's Science Diet Pequenos e Mini para Cães Filhotes Sabor Frango - 2.04kg",
    link: "https://amzn.to/46Eihf5?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/1254140/pexels-photo-1254140.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "dog food",
    description: "Ração premium para filhotes de raças pequenas e mini. Fórmula balanceada com frango, rica em proteínas e nutrientes essenciais para o desenvolvimento saudável.",
    price: "R$ 128,69",
    originalPrice: "R$ 142,99",
    rating: 4.7,
    reviews: 7226,
    category: "Ração",
    brand: "Hill's Science Diet",
    badge: "Escolha da Amazon",
    discount: "-10%"
  },
  {
    id: "2",
    title: "Dreamies Petisco Carne Tentadora Gatos Adultos 150G",
    link: "https://amzn.to/4lRBBd9?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/1741205/pexels-photo-1741205.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "cat treat",
    description: "Petisco irresistível para gatos adultos com sabor de carne. Textura crocante por fora e macia por dentro que os gatos adoram. Rico em vitaminas e minerais.",
    price: "R$ 17,99",
    originalPrice: "R$ 24,40",
    rating: 4.9,
    reviews: 3254,
    category: "Petiscos",
    brand: "Dreamies",
    badge: "Mais Vendido",
    discount: "-26%"
  },
  {
    id: "3",
    title: "Coleira Cachorro Gato Reflexiva Ajustável com Case Capa Rastreador GPS Airtag (Preta)",
    link: "https://amzn.to/3U8mOir?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "gps collar",
    description: "Coleira ajustável e reflexiva com compartimento especial para AirTag. Ideal para localizar seu pet. Material resistente e confortável para uso diário.",
    price: "R$ 39,90",
    originalPrice: "R$ 59,90",
    rating: 4.2,
    reviews: 79,
    category: "Acessórios",
    brand: "Gigasmart",
    badge: "Escolha da Amazon",
    discount: "-33%"
  },
  {
    id: "4",
    title: "Ração Premium Golden Fórmula para Cães Adultos Sabor Carne e Arroz - 15kg",
    link: "https://amzn.to/44HnaSa?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/1390361/pexels-photo-1390361.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "dog food",
    description: "Ração super premium com carne e arroz. Fórmula completa e balanceada para cães adultos de todas as raças. Rico em proteínas e fibras naturais.",
    price: "R$ 189,90",
    originalPrice: "R$ 229,90",
    rating: 4.6,
    reviews: 2847,
    category: "Ração",
    brand: "Golden",
    badge: "Super Premium",
    discount: "-17%"
  },
  {
    id: "5",
    title: "Brinquedo Mordedor Corda Dental para Cães - Kit com 3 Peças",
    link: "https://amzn.to/44MsXGa?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/1629781/pexels-photo-1629781.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "dog toy",
    description: "Kit com 3 brinquedos de corda para higiene dental. Ajuda a limpar os dentes e massagear as gengivas. Material resistente e seguro para cães de todos os tamanhos.",
    price: "R$ 24,90",
    originalPrice: "R$ 34,90",
    rating: 4.4,
    reviews: 1523,
    category: "Brinquedos",
    brand: "Pet Toys",
    badge: "Kit Completo",
    discount: "-29%"
  },
  {
    id: "6",
    title: "Shampoo Neutro para Cães e Gatos - 500ml",
    link: "https://amzn.to/4kCHaLO?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/6568461/pexels-photo-6568461.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "pet shampoo",
    description: "Shampoo neutro hipoalergênico para cães e gatos. Fórmula suave que limpa sem ressecar a pele. Ideal para pets com pele sensível.",
    price: "R$ 19,90",
    originalPrice: "R$ 29,90",
    rating: 4.5,
    reviews: 892,
    category: "Higiene",
    brand: "Pet Clean",
    badge: "Hipoalergênico",
    discount: "-33%"
  },
  {
    id: "7",
    title: "Comedouro e Bebedouro Automático Duplo Inox - 400ml cada",
    link: "https://amzn.to/4nNFSAb?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/1458916/pexels-photo-1458916.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "pet bowl",
    description: "Comedouro duplo em aço inoxidável com base antiderrapante. Fácil de limpar e higiênico. Ideal para cães e gatos de porte pequeno e médio.",
    price: "R$ 45,90",
    originalPrice: "R$ 65,90",
    rating: 4.7,
    reviews: 1247,
    category: "Comedouros",
    brand: "Pet Inox",
    badge: "Inox Premium",
    discount: "-30%"
  },
  {
    id: "8",
    title: "Areia Sanitária Bentonita para Gatos - 4kg",
    link: "https://amzn.to/4nL3IN1?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/1741205/pexels-photo-1741205.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "cat litter",
    description: "Areia sanitária de bentonita com alta absorção e controle de odores. Forma grumos sólidos para fácil remoção. Livre de poeira e fragrâncias artificiais.",
    price: "R$ 32,90",
    originalPrice: "R$ 42,90",
    rating: 4.3,
    reviews: 2156,
    category: "Higiene",
    brand: "Cat Litter",
    badge: "Controle de Odor",
    discount: "-23%"
  },
  {
    id: "9",
    title: "Casinha de Madeira para Cães Médios - Telhado Impermeável",
    link: "https://amzn.to/4lric2Y?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "dog house",
    description: "Casinha de madeira tratada com telhado impermeável. Proteção contra chuva e sol. Montagem fácil, ideal para cães de porte médio até 25kg.",
    price: "R$ 299,90",
    originalPrice: "R$ 399,90",
    rating: 4.6,
    reviews: 456,
    category: "Casinhas",
    brand: "Wood Pet",
    badge: "Madeira Tratada",
    discount: "-25%"
  },
  {
    id: "10",
    title: "Antipulgas e Carrapatos Spray Natural - 200ml",
    link: "https://amzn.to/44GI6bR?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/6568461/pexels-photo-6568461.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "flea spray",
    description: "Spray repelente natural contra pulgas e carrapatos. Fórmula com óleos essenciais, segura para pets e família. Proteção duradoura sem químicos agressivos.",
    price: "R$ 34,90",
    originalPrice: "R$ 49,90",
    rating: 4.4,
    reviews: 1834,
    category: "Saúde",
    brand: "Natural Pet",
    badge: "100% Natural",
    discount: "-30%"
  },
  {
    id: "11",
    title: "Ração Úmida Sachê para Gatos Adultos Mix de Sabores - Pack 12 unidades",
    link: "https://amzn.to/44MuzQe?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/1741205/pexels-photo-1741205.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "cat food pouch",
    description: "Pack com 12 sachês de ração úmida em sabores variados. Alimento completo e balanceado para gatos adultos. Rico em proteínas e com alta palatabilidade.",
    price: "R$ 89,90",
    originalPrice: "R$ 119,90",
    rating: 4.8,
    reviews: 3421,
    category: "Ração",
    brand: "Whiskas",
    badge: "Pack Econômico",
    discount: "-25%"
  },
  {
    id: "12",
    title: "Transportadora Plástica para Pets - Tamanho M (até 12kg)",
    link: "https://amzn.to/44MwjZM?tag=achoulevaai-20",
    image: "https://images.pexels.com/photos/1458916/pexels-photo-1458916.jpeg?auto=compress&cs=tinysrgb&w=400",
    dataAiHint: "pet carrier",
    description: "Transportadora resistente com ventilação adequada e trava de segurança. Ideal para viagens e consultas veterinárias. Fácil de limpar e montar.",
    price: "R$ 159,90",
    originalPrice: "R$ 199,90",
    rating: 4.5,
    reviews: 967,
    category: "Transporte",
    brand: "Pet Carrier",
    badge: "Viagem Segura",
    discount: "-20%"
  }
];