
import type { Deal } from './types';

export const deals: Deal[] = [
  {
    id: '1',
    title: 'Echo Dot (5th Gen)',
    description: 'Smart speaker with Alexa and clock. The best sounding Echo Dot yet, with clearer vocals and deeper bass.',
    image: 'https://placehold.co/600x400.png',
    link: '#',
    category: 'Electronics',
    price: '$49.99',
    originalPrice: '$59.99',
    discount: '17%',
    dataAiHint: 'smart speaker',
  },
  {
    id: '2',
    title: 'Kindle Paperwhite (16 GB)',
    description: 'Now with a 6.8" display and thinner borders, adjustable warm light, up to 10 weeks of battery life.',
    image: 'https://placehold.co/600x400.png',
    link: '#',
    category: 'Electronics',
    price: '$139.99',
    dataAiHint: 'e-reader book',
  },
  {
    id: '3',
    title: 'Instant Pot Duo 7-in-1',
    description: 'Electric Pressure Cooker, Slow Cooker, Rice Cooker, Steamer, Sauté, Yogurt Maker, Warmer & Sterilizer, 6 Quart.',
    image: 'https://placehold.co/600x400.png',
    link: '#',
    category: 'Home & Kitchen',
    price: '$79.00',
    originalPrice: '$99.99',
    discount: '21%',
    dataAiHint: 'kitchen appliance',
  },
  {
    id: '4',
    title: 'Atomic Habits by James Clear',
    description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones. A bestseller that has sold millions of copies.',
    image: 'https://placehold.co/600x400.png',
    link: '#',
    category: 'Books',
    price: '$11.98',
    originalPrice: '$27.00',
    discount: '56%',
    dataAiHint: 'self-help book',
  },
  {
    id: '5',
    title: 'Logitech MX Master 3S Mouse',
    description: 'Performance wireless mouse with ultra-fast scrolling, ergonomic design, 8K DPI, and quiet clicks.',
    image: 'https://placehold.co/600x400.png',
    link: '#',
    category: 'Computers',
    price: '$99.99',
    dataAiHint: 'computer mouse',
  },
  {
    id: '6',
    title: 'Anker PowerCore 10000',
    description: 'One of the smallest and lightest 10000mAh portable chargers. Provides almost three-and-a-half iPhone 8 charges.',
    image: 'https://placehold.co/600x400.png',
    link: '#',
    category: 'Electronics',
    price: '$21.99',
    dataAiHint: 'power bank',
  },
  {
    id: '7',
    title: 'LEGO Star Wars Millennium Falcon',
    description: 'Incredibly detailed 7,541-piece model of the iconic Corellian freighter. A must-have for Star Wars fans.',
    image: 'https://placehold.co/600x400.png',
    link: '#',
    category: 'Toys & Games',
    price: '$849.99',
    dataAiHint: 'lego spaceship',
  },
  {
    id: '8',
    title: 'Hydro Flask Water Bottle',
    description: 'Wide mouth straw lid, 32 oz. TempShield insulation eliminates condensation and keeps beverages cold up to 24 hours.',
    image: 'https://placehold.co/600x400.png',
    link: '#',
    category: 'Sports & Outdoors',
    price: '$44.95',
    dataAiHint: 'water bottle',
  }
];
